"""
Data Quality Page.

Displays data quality metrics generated by the
PayFlow Intelligence validation engine.

Author: Simba Munatsi
Project: PayFlow Intelligence Platform
"""

import streamlit as st

from components.api import run_pipeline


def render():
    """
    Render the Data Quality page.
    """

    st.header("📈 Data Quality Center")

    st.caption(
        "Monitor validation performance and overall data quality."
    )

    st.divider()

    if st.button(
        "▶ Refresh Data Quality",
        use_container_width=True,
        key="quality_refresh_button",
    ):

        with st.spinner(
            "Refreshing quality metrics..."
        ):

            result = run_pipeline()

        render_quality_dashboard(result)


# =====================================================
# Main Dashboard
# =====================================================

def render_quality_dashboard(result):

    quality = result["quality"]

    summary = result["summary"]

    # =====================================================
    # Overall Quality Score
    # =====================================================

    st.subheader("🏆 Overall Quality Score")

    score_col1, score_col2 = st.columns([1, 3])

    with score_col1:

        st.metric(
            "Quality Score",
            f"{quality['overall_score']}%"
        )

    with score_col2:

        st.progress(
            quality["overall_score"] / 100
        )

    st.divider()

    # =====================================================
    # Category Scorecards
    # =====================================================

    st.subheader("📊 Validation Categories")

    cols = st.columns(
        len(quality["categories"])
    )

    for col, category in zip(
        cols,
        quality["categories"],
    ):

        with col:

            st.metric(
                category["name"],
                f"{category['pass_rate']}%"
            )

            st.progress(
                category["pass_rate"] / 100
            )

            st.caption(
                f"✅ Passed: {category['passed']}"
            )

            st.caption(
                f"❌ Failed: {category['failed']}"
            )

            st.caption(
                f"Rules: {category['total']}"
            )

    st.divider()

    # =====================================================
    # Validation Summary
    # =====================================================

    st.subheader("📋 Validation Summary")

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Datasets",
            summary["datasets_loaded"]
        )

    with col2:

        st.metric(
            "Rules Executed",
            summary["validation_rules"]
        )

    with col3:

        st.metric(
            "Rules Passed",
            summary["rules_passed"]
        )

    with col4:

        st.metric(
            "Rules Failed",
            summary["rules_failed"]
        )

    st.divider()

    # =====================================================
    # Quality Breakdown Table
    # =====================================================

    st.subheader("📑 Quality Breakdown")

    rows = []

    for category in quality["categories"]:

        rows.append({

            "Category": category["name"],

            "Pass Rate (%)": category["pass_rate"],

            "Passed": category["passed"],

            "Failed": category["failed"],

            "Total Rules": category["total"],

        })

    st.dataframe(
        rows,
        width='stretch',
        hide_index=True,
    )

    st.caption(
        f"Last Updated: {summary['run_timestamp']}"
    )