"""
Warehouse Explorer Page.

Displays the analytics warehouse inventory.

Author: Simba Munatsi
Project: PayFlow Intelligence Platform
"""

import streamlit as st

from components.api import run_pipeline


def render():
    """
    Render the Warehouse Explorer page.
    """

    st.header("🏢 Warehouse Explorer")

    st.caption(
        "Browse the analytics warehouse tables generated by the pipeline."
    )

    st.divider()

    if st.button(
        "▶ Refresh Warehouse",
        width='stretch',
        key="warehouse_refresh_button",
    ):

        with st.spinner(
            "Loading warehouse..."
        ):

            result = run_pipeline()

        render_warehouse(result)


# =====================================================
# Warehouse Dashboard
# =====================================================

def render_warehouse(result):

    warehouse = result["warehouse"]

    tables = warehouse["tables"]

    total_tables = len(tables)

    dimension_tables = sum(
        1
        for table in tables
        if table["table_type"] == "Dimension"
    )

    fact_tables = sum(
        1
        for table in tables
        if table["table_type"] == "Fact"
    )

    # =====================================================
    # Summary
    # =====================================================

    st.subheader("📊 Warehouse Summary")

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Total Tables",
            total_tables,
        )

    with col2:

        st.metric(
            "Dimensions",
            dimension_tables,
        )

    with col3:

        st.metric(
            "Facts",
            fact_tables,
        )

    st.divider()

    # =====================================================
    # Warehouse Cards
    # =====================================================

    st.subheader("🗂 Warehouse Tables")

    for table in tables:

        icon = (
            "📦"
            if table["table_type"] == "Fact"
            else "📁"
        )

        with st.container():

            left, right = st.columns([4, 1])

            with left:

                st.markdown(
                    f"### {icon} {table['name']}"
                )

                st.caption(
                    table["table_type"]
                )

            with right:

                st.metric(
                    "Rows",
                    f"{table['rows']:,}"
                )

            st.divider()

    # =====================================================
    # Warehouse Inventory
    # =====================================================

    st.subheader("📋 Warehouse Inventory")

    inventory = []

    for table in tables:

        inventory.append({

            "Table": table["name"],

            "Type": table["table_type"],

            "Rows": table["rows"],

        })

    st.dataframe(

        inventory,

        width='stretch',

        hide_index=True,

    )